name: Release to GitHub
description: Creates a GitHub release from built artifacts

runs:
  using: composite
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v5
      with:
        merge-multiple: true

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.PROJECT_VERSION }}
        name: ${{ env.PROJECT_VERSION }}
        body: |
          ${{ env.CHANGELOG }}

          <details>
          <summary>Mods diff</summary>

          ${{ env.DIFF }}

          </details>
        files: |
          *.mrpack
          *.zip
        prerelease: ${{ env.RELEASE_TYPE != 'release' }}
